//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MachineFrameWork.MachineCommands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CarrierMachineCommands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CarrierMachineCommands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MachineFrameWork.MachineCommands.CarrierMachineCommands", typeof(CarrierMachineCommands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto_Mode.
        /// </summary>
        internal static string AutoMode {
            get {
                return ResourceManager.GetString("AutoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L2_CMD_DONE.
        /// </summary>
        internal static string CommandDone {
            get {
                return ResourceManager.GetString("CommandDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CM_Position_for_L2.
        /// </summary>
        internal static string CurrentAisle {
            get {
                return ResourceManager.GetString("CurrentAisle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L2_Destination_Aisle.
        /// </summary>
        internal static string DestinationAisle {
            get {
                return ResourceManager.GetString("DestinationAisle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L2_Destination_Row.
        /// </summary>
        internal static string DestinationRow {
            get {
                return ResourceManager.GetString("DestinationRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L2_Error_Data_Register.
        /// </summary>
        internal static string ErrorCommand {
            get {
                return ResourceManager.GetString("ErrorCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L2_Get_Cmd.
        /// </summary>
        internal static string Get {
            get {
                return ResourceManager.GetString("Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CM_Locked.
        /// </summary>
        internal static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L2_Max_Window_Limit.
        /// </summary>
        internal static string MaxWindow {
            get {
                return ResourceManager.GetString("MaxWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L2_Min_Window_Limit.
        /// </summary>
        internal static string MinWindow {
            get {
                return ResourceManager.GetString("MinWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L2_Move_Cmd.
        /// </summary>
        internal static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L2_Put_Cmd.
        /// </summary>
        internal static string Put {
            get {
                return ResourceManager.GetString("Put", resourceCulture);
            }
        }
    }
}
